apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.9.0
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-ingress-1b
  labels:
    app: nginx-ingress
spec:
  type: NodePort
  ports:
#  - nodePort: 32577
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
  selector:
    app: nginx-ingress
